### ISSUE TITLE
escholAPI migration to AL2023

### ISSUE THREAD

**Issue by myucekul** [eScholarship/escholApi#75]
- [x] Build with Ruby 3.2, Node 20 in AL2023 in dev env
- [x] Update GraphQL from version 1 to 2
- [x] Update code and test
- [x] Investigate and resolve problems
- [x] Build package to deploy in EB
- [x] Ask team for PR review and further testing
- [x] Troubleshoot and resolve issues

**Comment by myucekul** [comment]
19:35:18 [rerun] Escholapi Launch Failed
/home/ec2-user/repos/escholApi/escholApi/gems/ruby/3.2.0/gems/rerun-0.13.1/lib/rerun/watcher.rb:53:in `block in sanitize_dirs': undefined method `exists?' for FileTest:Module (NoMethodError)

**Comment by myucekul** [comment]
Updated rerun to version 0.14.0

Another error:
Parsing options from the first comment line is deprecated!
/home/ec2-user/repos/escholApi/escholApi/gems/ruby/3.2.0/gems/graphql-1.12.16/lib/graphql/deprecated_dsl.rb:43:in `include': Refinement#include has been removed (TypeError)

**Comment by myucekul** [comment]
Updated graphQL to version 2.4.8

Now error is in our code
20:02:59 [rerun] Rerun (9508) running Escholapi (9509)
Parsing options from the first comment line is deprecated!
/home/ec2-user/repos/escholApi/escholApi/lib/sharedTypes.rb:3:in `<top (required)>': uninitialized constant GraphQL::ScalarType (NameError)
